// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: module/task_exec.proto

package module

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TaskExec with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskExec) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskExec with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TaskExecMultiError, or nil
// if none found.
func (m *TaskExec) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskExec) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TaskId

	// no validation rules for Context

	// no validation rules for Status

	// no validation rules for Result

	// no validation rules for Return

	// no validation rules for StartTime

	// no validation rules for FinishTime

	// no validation rules for CreateTime

	// no validation rules for UpdateTime

	if len(errors) > 0 {
		return TaskExecMultiError(errors)
	}

	return nil
}

// TaskExecMultiError is an error wrapping multiple validation errors returned
// by TaskExec.ValidateAll() if the designated constraints aren't met.
type TaskExecMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskExecMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskExecMultiError) AllErrors() []error { return m }

// TaskExecValidationError is the validation error returned by
// TaskExec.Validate if the designated constraints aren't met.
type TaskExecValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskExecValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskExecValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskExecValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskExecValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskExecValidationError) ErrorName() string { return "TaskExecValidationError" }

// Error satisfies the builtin error interface
func (e TaskExecValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskExec.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskExecValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskExecValidationError{}
